"""add created_at to review

Revision ID: 566ed4d192f1
Revises: 95824779a15b
Create Date: 2026-05-12 23:33:50.456149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566ed4d192f1'
down_revision = '95824779a15b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key('fk_review_movie_id', 'movie', ['movie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint('fk_review_movie_id', type_='foreignkey')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
