"""add movie model

Revision ID: 95824779a15b
Revises: 9a696f4ac7da
Create Date: 2026-05-12 16:07:40.799171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95824779a15b'
down_revision = '9a696f4ac7da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'movie', ['movie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('movie')
    # ### end Alembic commands ###
