"""empty message

Revision ID: 968f4c8109bc
Revises: ff10894588f1
Create Date: 2026-05-14 21:02:55.090253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968f4c8109bc'
down_revision = 'ff10894588f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
