"""add flagged-reason to Review model

Revision ID: ff10894588f1
Revises: 566ed4d192f1
Create Date: 2026-05-13 11:50:20.540381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff10894588f1'
down_revision = '566ed4d192f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('flag_reason')

    # ### end Alembic commands ###
